/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.liferayasif.sb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Menu service. Represents a row in the &quot;AA_Menu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.liferayasif.sb.model.impl.MenuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.liferayasif.sb.model.impl.MenuImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Menu
 * @see org.liferayasif.sb.model.impl.MenuImpl
 * @see org.liferayasif.sb.model.impl.MenuModelImpl
 * @generated
 */
@ProviderType
public interface MenuModel extends BaseModel<Menu> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a menu model instance should use the {@link Menu} interface instead.
	 */

	/**
	 * Returns the primary key of this menu.
	 *
	 * @return the primary key of this menu
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this menu.
	 *
	 * @param primaryKey the primary key of this menu
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the menu ID of this menu.
	 *
	 * @return the menu ID of this menu
	 */
	public long getMenuId();

	/**
	 * Sets the menu ID of this menu.
	 *
	 * @param menuId the menu ID of this menu
	 */
	public void setMenuId(long menuId);

	/**
	 * Returns the type of this menu.
	 *
	 * @return the type of this menu
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this menu.
	 *
	 * @param type the type of this menu
	 */
	public void setType(String type);

	/**
	 * Returns the food name of this menu.
	 *
	 * @return the food name of this menu
	 */
	@AutoEscape
	public String getFoodName();

	/**
	 * Sets the food name of this menu.
	 *
	 * @param foodName the food name of this menu
	 */
	public void setFoodName(String foodName);

	/**
	 * Returns the price of this menu.
	 *
	 * @return the price of this menu
	 */
	public long getPrice();

	/**
	 * Sets the price of this menu.
	 *
	 * @param price the price of this menu
	 */
	public void setPrice(long price);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Menu menu);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Menu> toCacheModel();

	@Override
	public Menu toEscapedModel();

	@Override
	public Menu toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}